// Code generated by go2go; DO NOT EDIT.


//line ring.go2:1
package go2

//line ring.go2:1
import (
//line ring.go2:1
 "bytes"
//line ring.go2:1
 "sync"
//line ring.go2:1
 "time"
//line ring.go2:1
)

//line ring.go2:1
type Importable୦ int
//line ring.go2:1
type _ bytes.Buffer
//line ring.go2:1
type _ sync.Cond

//line ring.go2:1
const _ = time.ANSIC
