// Code generated by go2go; DO NOT EDIT.


//line slice.go2:1
package go2

//line slice.go2:1
import (
//line slice.go2:1
 "bytes"
//line slice.go2:1
 "sync"
//line slice.go2:1
 "time"
//line slice.go2:1
)

//line slice.go2:1
type _ bytes.Buffer
//line slice.go2:1
type _ sync.Cond

//line slice.go2:1
const _ = time.ANSIC
